import { Geist, Geist_Mono } from 'next/font/google';
import Providers from './providers';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Links = [
  { link: '/todo-list', title: 'Todo List' },
  { link: '/query', title: 'Query' },
  { link: '/counter', title: 'Counter' },
];

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ul className='flex gap-[10px] p-2'>
          {Links.map((item) => (
            <li key={item.link}>
              <Link href={`${item.link}`} className='btn btn-ghost'>
                {item.title}
              </Link>
            </li>
          ))}
        </ul>
        <main className='p-4'>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
